# Use an official Nginx image from the Docker Hub
FROM nginx:alpine

# Copy the HTML files into the Nginx directory
COPY ./ /usr/share/nginx/html/

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
